### PR TITLE
Remove deprecated multicall

### LINKED ISSUE #3: Use of __multicall__ is deprecated
Generates deprecation-warning.

### PR DESCRIPTION
**Pull request by BeyondEvil**
**multicall** is deprecated since <version>. My changes should get rid of the warning:

"pytest-browsermob-proxy/pytest_browsermob_proxy.py:119 'pytest_runtest_makereport' hook uses deprecated **multicall** argument"

Test ran successfully.

Any input @davehunt ?

Fixes #3

### CODE REVIEW

**Comment by davehunt** [comment]
Thanks @BeyondEvil! I no longer use or maintain this plugin - are you interested in taking ownership of it?

**Comment by BeyondEvil** [comment]
@davehunt I'd be happy to! However, up till now I've only been a user of python-packages so I would require some initial hand-holding to learn how to manage and distribute them. Maybe there are some good tutorials out there?

**Comment by davehunt** [comment]
First, let me say that I'm no longer maintaining this plugin partly because we didn't have enough of a need for running our tests through BrowserMob Proxy, but also partly because I feel it isn't the correct approach to have a pytest plugin manage the proxy process. If I revisit this in the future, I'm more likely to have the proxy started by another mechanism, such as a CI server, potentially even using Docker. It may still make sense to have a plugin that provides fixtures that allow easy access to the proxy client, but handling the process itself feels like too much.

The [Python Packaging User Guide](https://packaging.python.org/distributing/) is a good place to start learning about distributing Python packages. You already have a fork of this repository, so when you're ready I can just add you to the [PyPI project](https://pypi.python.org/pypi/pytest-browsermob-proxy) as a maintainer.

**Comment by BeyondEvil** [comment]
Ah, interesting @davehunt !

We use Docker at our shop, so that sounds like it could be a good approach. I agree with the premise of the plugin (or even pytest as such) owning the proxy process.

I'll still be happy to take over ownership for the time being. If I make some headway with the Docker approach I'll let you know. Cool?

**Comment by BeyondEvil** [comment]
Bringing in my pnc to take part of the conversation. @Mayestril

**Pull request closed without merging**
